# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
