# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('E', 'Equipment')], default=True, max_length=1),
        ),
    ]
