# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200419_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('M', 'Mens'), ('W', 'Womens'), ('E', 'Equipment')], default=False, max_length=6),
        ),
    ]
