# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-28 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200422_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens'), ('Equipment', 'Equipment')], default=False, max_length=254),
        ),
    ]
