# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200428_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('M', 'Mens'), ('W', 'Womens'), ('E', 'Equipment')], default=False, max_length=254),
        ),
    ]
