# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-04 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200428_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('M', 'Mens'), ('W', 'Womens'), ('E', 'Equipment')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
