# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200504_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Mens', 'M'), ('Womens', 'W'), ('Equipment', 'E')], default='', max_length=254),
        ),
    ]
