# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.TextField(choices=[('M', 'Mens'), ('W', 'Womens'), ('E', 'Equipment')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default='', max_length=254),
        ),
    ]
